import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/footer/footer'
import Header from '../components/header/header'
import Pick from '../components/pick/pick'
// import styles from '../styles/Home.module.css'

import homeStyle from '../styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Pick</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div className={homeStyle.main}>
        <Pick/>
      </div>
      <Footer/>
    </>
  )
}
